name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code from your repository
      
      # Replace with commands relevant to your project
      - name: Run custom commands
        run: |
          echo "You made it to create you first ci/cd."
